apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: demo1
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: demo
        image: "scraly/test.dockerapp:latest"
      imagePullSecrets:
        - name: regsecret-prod
